### ISSUE TITLE
World interaction?

### ISSUE THREAD

**Issue by max1220** [BeboKhouja/Lua-Runtime-Mod#1]
Am I mistaken, or does this not yet support any world interactions(like reading/placing a block, creating/modifying entities, etc.), and can only create GUIs?

It would be useful to have basic world interaction even without an (external) library mod.

**Comment by BeboKhouja** [comment]
I would support that but only in server side
If we'd support that on client side, then that could be considered cheating, and since Modrinth and CurseForge doesnt allow hack clients or some sort, then the mod could be removed from Modrinth or CurseForge.

**Comment by lv37** [comment]
> If we'd support that on client side, then that could be considered cheating, and since Modrinth and CurseForge doesnt allow hack clients or some sort, then the mod could be removed from Modrinth or CurseForge.

Isn't this mod just basically a Lua mod loader? And I'm pretty sure mod loaders on Modrinth are allowed to have any functionality, it just doesn't have to have built-in cheats.

[ChatTriggers](https://modrinth.com/mod/chattriggers) is a similar mod that has this functionality that is on Modrinth, so I think it's fine to support it client side.

**Comment by max1220** [comment]
Both server-side and client-side support for basic world interaction would be great and could be used in a non-cheating way, but I get why it might be problematic for vanilla survival scenarios when you could automate certain things on the client.

That being said, I would really like server-side support for world interaction - It would be up to the server operator to make sure the scripts don't allow cheating anyway.
